README.md
Added readme instructions for deploying separate e/d node
=> CLD-600: Documentation for K8s separate E/D implementation

charts/templates/statefulset.yaml, charts/values.yaml
Add Creation of default App-server into new groups created.
Removing the loop previously done by using curl retry functionality
=> Add App-Services App-server creation

README.md, charts/templates/statefulset.yaml, charts/values.yaml, test/template/pod_priority_templ_test.go
Added config for pod priorityClassName and template test
=> CLD-667: Provide Option to Configure Pod Priority

Jenkinsfile
Jenkins pipeline is failing on all branches due to outdated Docker version.
=> Update Docker version

README.md, charts/templates/statefulset.yaml, charts/values.yaml, test/e2e/env_param_test.go, test/template/env_param_templ_test.go
- Added option to install converters
- Added option to add MarkLogic license
- Added template and e2e tests for all new parameters
=> CLD-699 & CLD-698 add converters and license params

README.md
* added documentation for upgrades
=> CLD-718: added documentation for MarkLogic and Helm chart upgrades (#92)

Jenkinsfile, makefile
- Add artifact archive and cleanup
- Remove HTML publisher as we don't use it in this pipeline
- Remove option description in HC step as we don't provide any options now
=> CLD-792 add results cleanup

Jenkinsfile
Switch from @marklogic to @progress in the pipeline to fix mail delivery.
=> CLD-817 Update email domain to progress.

Jenkinsfile
This should fix the jenkins failures
=> CLD-932 Update to the latest Docker version

Jenkinsfile
This should fix the broken pipeline on develop.
=> Update ML version

Jenkinsfile
Jira ID pattern was updated to support the new Jira instance.
=> MLE-11449: update jira ID pattern

Jenkinsfile, makefile, test/hc_e2e.sh
pod names got shortened in charts and not in the HC tests. This PR should fix it.
=> MLE-11843 fix HC tests

test/e2e/upgrade_test.go
increased retry interval for health check after helm upgrade
=> MLE-12244: Upgrade test is failing on K8s pipeline

Jenkinsfile
=> MLE-13388 update Jira URL

test/e2e/install_test.go, test/e2e/tls_test.go, test/hugePages/huge_pages_test.go, test/testUtil/ml_ready_check.go
- Added util fn for MarkLogic ready check.
=> MLE-4129: Create util function for ML readiness

charts/Chart.yaml, charts/templates/_helpers.tpl, charts/templates/configmap-haproxy.yaml, charts/values.yaml
1. fix the bug regarding update with service name 
2. update the Chart version to 1.1.2
3. update the image to 11.2.0-centos-1.1.2
=> MLE-13841 backward compatibility bug fix

test/e2e/path_based_test.go, test/test_data/path_based_test_data/test-server.json, test/test_data/values/tls_pbr_appser_values.yaml
- added e2e test for additional AppServer
=> MLE-4174: Kubernetes HA Proxy test automation when creating new APP Server

.gitignore, Jenkinsfile, makefile
Updated Kubernetes version list to use full version and switched default to 1.28
Also added a new parameter that allows to run one e2e test.
=> MLE-14440 pipeline fix

makefile, test/e2e/admin_secrets_test.go, test/e2e/backup_restore_test.go, test/e2e/clustering_test.go, test/e2e/env_param_test.go, test/e2e/install_test.go, test/e2e/path_based_test.go, test/e2e/ready_test.go, test/e2e/scaling_test.go, test/e2e/separate_nodes_test.go, test/e2e/tls_test.go, test/e2e/upgrade_test.go, test/hugePages/huge_pages_test.go, test/template/tls_param_template_test.go, test/testUtil/restart_pod.go, test/test_data/values/tls_pbr_appser_values.yaml, test/test_data/values/tls_template_values.yaml
added restart util fn and updated existing e2e tests with after restart checks
=> MLE-12270: added restart util fn and updated e2e tests with post restart checks

Jenkinsfile, makefile, test/e2e/admin_secrets_test.go, test/e2e/backup_restore_test.go, test/e2e/clustering_test.go, test/e2e/env_param_test.go, test/e2e/install_test.go, test/e2e/path_based_test.go, test/e2e/ready_test.go, test/e2e/scaling_test.go, test/e2e/separate_nodes_test.go, test/e2e/tls_test.go, test/e2e/upgrade_test.go, test/hugePages/huge_pages_test.go, test/testUtil/helm_install.go, test/testUtil/helm_upgrade.go, test/testUtil/pod_running_check.go, test/test_data/values/tls_enode_values.yaml
Note: This is a draft PR for adding upgrade tests and a stage and option in Jenkins for running it nightly.
=> MLE-13839: added changes for helm upgrade e2e test

Jenkinsfile, makefile, test/e2e/admin_secrets_test.go, test/e2e/backup_restore_test.go, test/e2e/clustering_test.go, test/e2e/env_param_test.go, test/e2e/install_test.go, test/e2e/path_based_test.go, test/e2e/ready_test.go, test/e2e/scaling_test.go, test/e2e/separate_nodes_test.go, test/e2e/tls_test.go, test/e2e/upgrade_test.go, test/hugePages/huge_pages_test.go, test/testUtil/helm_install.go, test/testUtil/helm_upgrade.go, test/testUtil/pod_running_check.go, test/test_data/values/tls_enode_values.yaml
* added changes for helm upgrade e2e test
=> MLE-13839: added changes for helm upgrade e2e test (#250)

charts/templates/configmap-scripts.yaml, test/e2e/backup_restore_test.go, test/e2e/clustering_test.go, test/e2e/group_cfg_test.go, test/e2e/install_test.go, test/e2e/path_based_test.go, test/e2e/scaling_test.go, test/e2e/separate_nodes_test.go, test/e2e/tls_test.go, test/e2e/upgrade_test.go, test/testUtil/ml_ready_check.go
Refactor AddRetryCondition to handle nil pointer issue correctly
Group Change Test does not testing change group via values file, instead change the group directly with Rest call. Need to rewrite the test.
Refactor install test by adding retry logic
Add retry to configure_group function in postStart Script.
=> MLE-15631 Improve Tests

README.md
MLE-17900/Update code blocks and fix some syntax
(cherry picked from commit 674801d5fd84ea311f35a43b18ea3d292ba554c7)
=> Release 2.0.0 with README update
